# Generated by Django 5.2.10 on 2026-02-01 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veil_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage_limit',
            name='last_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
