# Generated by Django 5.2.10 on 2026-02-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veil_app', '0002_alter_usage_limit_last_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificaton',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
